SW4#sh run
Building configuration...

Current configuration : 2562 bytes
!
! Last configuration change at 22:12:20 UTC Sat Apr 4 2026
!
version 15.2
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
service compress-config
!
hostname SW4
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
!
!
!
ip vrf MGMT
!
!
!
no ip domain-lookup
ip cef
ipv6 unicast-routing
ipv6 cef
!
!
spanning-tree mode pvst
spanning-tree extend system-id
!
vlan internal allocation policy ascending
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Port-channel1
 switchport trunk encapsulation dot1q
 switchport mode trunk
!
interface Ethernet0/0
 description to_SW3
 switchport trunk encapsulation dot1q
 switchport mode trunk
!
interface Ethernet0/1
 description to_SW2
 switchport trunk encapsulation dot1q
 switchport mode trunk
!
interface Ethernet0/2
 description to_SW5
 switchport trunk encapsulation dot1q
 switchport mode trunk
 channel-group 1 mode active
!
interface Ethernet0/3
 description to_SW5
 switchport trunk encapsulation dot1q
 switchport mode trunk
 channel-group 1 mode active
!
interface Ethernet1/0
 description to_R12
 switchport trunk encapsulation dot1q
 switchport mode trunk
!
interface Ethernet1/1
 description to_R13
 switchport trunk encapsulation dot1q
 switchport mode trunk
!
interface Ethernet1/2
!
interface Ethernet1/3
!
interface Vlan10
 description client_10_gw
 ip address 10.10.10.1 255.255.255.0
 standby 10 ip 10.10.10.254
 standby 10 priority 150
 standby 10 preempt
 ipv6 address 2001:DB8:10:10::1/64
 ipv6 ospf 1 area 10
!
interface Vlan20
 description client_20_gw
 ip address 10.10.20.1 255.255.255.0
 standby 20 ip 10.10.20.254
 standby 20 priority 150
 standby 20 preempt
 ipv6 address 2001:DB8:10:20::1/64
 ipv6 ospf 1 area 10
!
interface Vlan95
 description P2P_R13
 ip address 192.168.98.14 255.255.255.252
 ipv6 address 2001:DB8:98:12::2/64
 ipv6 ospf 1 area 10
!
interface Vlan98
 description P2P_R12
 ip address 192.168.98.2 255.255.255.252
 ipv6 address 2001:DB8:98::2/64
 ipv6 ospf 1 area 10
!
interface Vlan99
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.99.4 255.255.255.0
!
router ospf 1
 router-id 4.4.4.4
 network 10.10.10.0 0.0.0.255 area 10
 network 10.10.20.0 0.0.0.255 area 10
 network 192.168.98.0 0.0.0.3 area 10
 network 192.168.98.12 0.0.0.3 area 10
!
ip forward-protocol nd
!
no ip http server
no ip http secure-server
!
ip route vrf MGMT 0.0.0.0 0.0.0.0 192.168.99.254
!
!
ipv6 router ospf 1
 router-id 4.4.4.4
!
!
!
!
control-plane
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
!
!
end

SW4#
