R25#sh run
Building configuration...

Current configuration : 1430 bytes
!
! Last configuration change at 00:51:29 UTC Wed Apr 1 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R25
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback100
 description Test_Inet
 ip address 8.8.8.8 255.255.255.255
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.25 255.255.255.255
!
interface Ethernet0/0
 description P2P_R23
 ip address 192.168.98.66 255.255.255.252
!
interface Ethernet0/1
 description P2P_R27
 ip address 192.168.98.94 255.255.255.252
!
interface Ethernet0/2
 description P2P_R26
 ip address 192.168.98.82 255.255.255.252
!
interface Ethernet0/3
 description P2P_R28
 ip address 192.168.98.90 255.255.255.252
!
interface Ethernet1/0
 no ip address
 shutdown
!
interface Ethernet1/1
 no ip address
 shutdown
!
interface Ethernet1/2
 no ip address
 shutdown
!
interface Ethernet1/3
 no ip address
 shutdown
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R25#
