VPC1> show ip

NAME        : VPC1[1]
IP/MASK     : 10.10.10.10/24
GATEWAY     : 10.10.10.254
DNS         :
MAC         : 00:50:79:66:68:01
LPORT       : 20000
RHOST:PORT  : 127.0.0.1:30000
MTU         : 1500

VPC1>

VPC1> show ipv6

NAME              : VPC1[1]
LINK-LOCAL SCOPE  : fe80::250:79ff:fe66:6801/64
GLOBAL SCOPE      : 2001:db8:10:10::10/64
DNS               :
ROUTER LINK-LAYER : aa:bb:cc:80:40:00
MAC               : 00:50:79:66:68:01
LPORT             : 20000
RHOST:PORT        : 127.0.0.1:30000
MTU:              : 1500

VPC1>

