VPCS> sh ip

NAME        : VPCS[1]
IP/MASK     : 10.20.10.10/24
GATEWAY     : 10.20.10.254
DNS         :
MAC         : 00:50:79:66:68:0b
LPORT       : 20000
RHOST:PORT  : 127.0.0.1:30000
MTU         : 1500

VPCS>
