R13#sh run
Building configuration...

Current configuration : 2401 bytes
!
! Last configuration change at 21:34:42 UTC Sat Apr 4 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R13
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
no ip domain lookup
ip cef
ipv6 unicast-routing
ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.13 255.255.255.255
!
interface Ethernet0/0
 description to_SW5
 no ip address
!
interface Ethernet0/0.96
 description P2P_SW5
 encapsulation dot1Q 96
 ip address 192.168.98.9 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 10
 ipv6 address 2001:DB8:98:8::1/64
 ipv6 ospf 1 area 10
 ipv6 ospf network point-to-point
!
interface Ethernet0/1
 description to_SW4
 no ip address
!
interface Ethernet0/1.95
 description P2P_SW4
 encapsulation dot1Q 95
 ip address 192.168.98.13 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 10
 ipv6 address 2001:DB8:98:12::1/64
 ipv6 ospf 1 area 10
 ipv6 ospf network point-to-point
!
interface Ethernet0/2
 description P2P_R15
 ip address 192.168.98.25 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 0
 ipv6 address 2001:DB8:98:24::1/64
 ipv6 ospf 1 area 0
 ipv6 ospf network point-to-point
!
interface Ethernet0/3
 description P2P_R14
 ip address 192.168.98.21 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 0
 ipv6 address 2001:DB8:98:20::1/64
 ipv6 ospf 1 area 0
 ipv6 ospf network point-to-point
!
interface Ethernet1/0
 no ip address
 shutdown
!
interface Ethernet1/1
 no ip address
 shutdown
!
interface Ethernet1/2
 no ip address
 shutdown
!
interface Ethernet1/3
 no ip address
 shutdown
!
router ospf 1
 router-id 13.13.13.13
 area 10 stub no-summary
 network 192.168.98.8 0.0.0.3 area 10
 network 192.168.98.12 0.0.0.3 area 10
 network 192.168.98.20 0.0.0.3 area 0
 network 192.168.98.24 0.0.0.3 area 0
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
ipv6 router ospf 1
 router-id 13.13.13.13
 area 10 stub no-summary
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R13#
