R17#sh run
Building configuration...

Current configuration : 1809 bytes
!
! Last configuration change at 18:48:30 UTC Sun Apr 5 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R17
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
no ip domain lookup
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
key chain EIGRP-KEY
 key 1
  key-string CISCO
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.17 255.255.255.255
!
interface Ethernet0/0
 description to_SW9
 no ip address
!
interface Ethernet0/0.95
 description P2P_SW9
 encapsulation dot1Q 95
 ip address 192.168.98.126 255.255.255.252
 ip summary-address eigrp 1 10.20.0.0 255.255.0.0
!
interface Ethernet0/1
 description P2P_R18
 ip address 192.168.98.105 255.255.255.252
!
interface Ethernet0/2
 description to_SW10
 no ip address
!
interface Ethernet0/2.97
 description P2P_SW10
 encapsulation dot1Q 97
 ip address 192.168.98.117 255.255.255.252
 ip summary-address eigrp 1 10.20.0.0 255.255.0.0
!
interface Ethernet0/3
 no ip address
 shutdown
!
!
router eigrp PETERSBURG
 !
 address-family ipv4 unicast autonomous-system 1
  !
  af-interface default
   authentication mode md5
   authentication key-chain EIGRP-KEY
  exit-af-interface
  !
  topology base
  exit-af-topology
  network 192.168.98.104 0.0.0.3
  network 192.168.98.116 0.0.0.3
  network 192.168.98.124 0.0.0.3
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R17#
