R21#sh run
Building configuration...

Current configuration : 1900 bytes
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R21
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
no ip domain lookup
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.21 255.255.255.255
!
interface Ethernet0/0
 description P2P_R15
 ip address 192.168.98.46 255.255.255.252
!
interface Ethernet0/1
 description P2P_R22
 ip address 192.168.98.49 255.255.255.252
!
interface Ethernet0/2
 description P2P_R24
 ip address 192.168.98.53 255.255.255.252
!
interface Ethernet0/3
 no ip address
 shutdown
!
interface Ethernet1/0
 no ip address
 shutdown
!
interface Ethernet1/1
 no ip address
 shutdown
!
interface Ethernet1/2
 no ip address
 shutdown
!
interface Ethernet1/3
 no ip address
 shutdown
!
router bgp 301
 bgp router-id 21.21.21.21
 bgp log-neighbor-changes
 neighbor 192.168.98.45 remote-as 1001
 neighbor 192.168.98.45 description eBGP_to_Moscow_R15
 neighbor 192.168.98.50 remote-as 101
 neighbor 192.168.98.50 description eBGP_to_Kitorn_R22
 neighbor 192.168.98.54 remote-as 520
 neighbor 192.168.98.54 description eBGP_to_Triada_R24
 !
 address-family ipv4
  network 192.168.98.44 mask 255.255.255.252
  network 192.168.98.48 mask 255.255.255.252
  network 192.168.98.52 mask 255.255.255.252
  neighbor 192.168.98.45 activate
  neighbor 192.168.98.50 activate
  neighbor 192.168.98.54 activate
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R21#
