R15#sh run
Building configuration...

Current configuration : 2631 bytes
!
! Last configuration change at 14:51:03 UTC Sat Apr 11 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R15
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
no ip domain lookup
ip cef
ipv6 unicast-routing
ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 description iBGP_Router_ID
 ip address 15.15.15.15 255.255.255.255
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.15 255.255.255.255
!
interface Ethernet0/0
 description P2P_R13
 ip address 192.168.98.26 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 0
 ipv6 address 2001:DB8:98:24::2/64
 ipv6 ospf 1 area 0
 ipv6 ospf network point-to-point
!
interface Ethernet0/1
 description P2P_R12
 ip address 192.168.98.30 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 0
 ipv6 address 2001:DB8:98:28::2/64
 ipv6 ospf 1 area 0
 ipv6 ospf network point-to-point
!
interface Ethernet0/2
 description P2P_R21
 ip address 192.168.98.45 255.255.255.252
!
interface Ethernet0/3
 description P2P_R20
 ip address 192.168.98.38 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 102
 ipv6 address 2001:DB8:98:36::2/64
 ipv6 ospf 1 area 102
 ipv6 ospf network point-to-point
!
router ospf 1
 router-id 15.15.15.15
 redistribute bgp 1001 subnets
 network 15.15.15.15 0.0.0.0 area 0
 network 192.168.98.24 0.0.0.3 area 0
 network 192.168.98.28 0.0.0.3 area 0
 network 192.168.98.36 0.0.0.3 area 102
 default-information originate always
!
router bgp 1001
 bgp router-id 15.15.15.15
 bgp log-neighbor-changes
 neighbor 14.14.14.14 remote-as 1001
 neighbor 14.14.14.14 description iBGP_to_R14
 neighbor 14.14.14.14 update-source Loopback0
 neighbor 192.168.98.46 remote-as 301
 neighbor 192.168.98.46 description eBGP_to_Lamas_R21
 !
 address-family ipv4
  network 10.10.10.0 mask 255.255.255.0
  network 10.10.20.0 mask 255.255.255.0
  network 192.168.98.0
  network 192.168.98.44 mask 255.255.255.252
  neighbor 14.14.14.14 activate
  neighbor 14.14.14.14 next-hop-self
  neighbor 192.168.98.46 activate
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
ipv6 router ospf 1
 router-id 15.15.15.15
 default-information originate always
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R15#
