R12#sh run
Building configuration...

Current configuration : 1665 bytes
!
! Last configuration change at 13:45:48 UTC Sat Jan 17 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R12
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.12 255.255.255.255
!
interface Ethernet0/0
 description to_SW4
 no ip address
!
interface Ethernet0/0.98
 description P2P_SW4
 encapsulation dot1Q 98
 ip address 192.168.98.1 255.255.255.252
!
interface Ethernet0/0.99
 description MGMT_SW_GW_to_SW4
 encapsulation dot1Q 99
 ip vrf forwarding MGMT
 ip address 192.168.99.254 255.255.255.0
!
interface Ethernet0/1
 description to_SW5
 no ip address
!
interface Ethernet0/1.97
 description P2P_SW5
 encapsulation dot1Q 97
 ip address 192.168.98.5 255.255.255.252
!
interface Ethernet0/2
 description P2P_R14
 ip address 192.168.98.17 255.255.255.252
!
interface Ethernet0/3
 description P2P_R15
 ip address 192.168.98.29 255.255.255.252
!
interface Ethernet1/0
 no ip address
 shutdown
!
interface Ethernet1/1
 no ip address
 shutdown
!
interface Ethernet1/2
 no ip address
 shutdown
!
interface Ethernet1/3
 no ip address
 shutdown
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R12#
