SW29#sh run
Building configuration...

Current configuration : 1248 bytes
!
! Last configuration change at 15:19:16 UTC Sat Jan 17 2026
!
version 15.2
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
service compress-config
!
hostname SW29
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
!
!
!
!
!
ip cef
no ipv6 cef
!
!
spanning-tree mode pvst
spanning-tree extend system-id
!
vlan internal allocation policy ascending
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Ethernet0/0
 switchport access vlan 10
 switchport mode access
!
interface Ethernet0/1
 switchport access vlan 20
 switchport mode access
!
interface Ethernet0/2
 description P2P_R28
 switchport trunk encapsulation dot1q
 switchport mode trunk
!
interface Ethernet0/3
!
interface Vlan10
 description client_10_gw
 ip address 10.30.10.1 255.255.255.0
!
interface Vlan20
 description client_20_gw
 ip address 10.30.20.1 255.255.255.0
!
interface Vlan98
 description P2P_R28
 ip address 192.168.98.97 255.255.255.252
!
interface Vlan99
 description MGMT
 ip address 192.168.99.29 255.255.255.0
!
ip default-gateway 192.168.99.253
ip forward-protocol nd
!
no ip http server
no ip http secure-server
!
!
!
!
!
!
control-plane
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
!
!
end

SW29#
