R14#sh run
Building configuration...

Current configuration : 2385 bytes
!
! Last configuration change at 21:32:31 UTC Sat Apr 4 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R14
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
ip vrf MGMT
!
!
!
!
no ip domain lookup
ip cef
ipv6 unicast-routing
ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback199
 description MGMT
 ip vrf forwarding MGMT
 ip address 192.168.199.14 255.255.255.255
!
interface Ethernet0/0
 description P2P_R12
 ip address 192.168.98.18 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 0
 ipv6 address 2001:DB8:98:16::2/64
 ipv6 ospf 1 area 0
 ipv6 ospf network point-to-point
!
interface Ethernet0/1
 description P2P_R13
 ip address 192.168.98.22 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 0
 ipv6 address 2001:DB8:98:20::2/64
 ipv6 ospf 1 area 0
 ipv6 ospf network point-to-point
!
interface Ethernet0/2
 description P2P_R22
 ip address 192.168.98.42 255.255.255.252
!
interface Ethernet0/3
 description P2P_R19
 ip address 192.168.98.34 255.255.255.252
 ip ospf network point-to-point
 ip ospf 1 area 101
 ipv6 address 2001:DB8:98:32::2/64
 ipv6 ospf 1 area 101
 ipv6 ospf network point-to-point
!
router ospf 1
 router-id 14.14.14.14
 area 101 stub no-summary
 area 101 filter-list prefix BLOCK_AREA101 out
 network 192.168.98.16 0.0.0.3 area 0
 network 192.168.98.20 0.0.0.3 area 0
 network 192.168.98.32 0.0.0.3 area 101
 default-information originate always
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
ip prefix-list BLOCK_AREA101 seq 5 deny 10.101.1.0/24
ip prefix-list BLOCK_AREA101 seq 10 deny 10.101.2.0/24
ip prefix-list BLOCK_AREA101 seq 15 permit 0.0.0.0/0 le 32
ipv6 router ospf 1
 router-id 14.14.14.14
 area 101 stub no-summary
 area 101 filter-list prefix BLOCK_AREA101 out
 default-information originate always
!
!
!
ipv6 prefix-list BLOCK_AREA101 seq 5 deny 2001:DB8:101:1::/64
ipv6 prefix-list BLOCK_AREA101 seq 10 deny 2001:DB8:101:2::/64
ipv6 prefix-list BLOCK_AREA101 seq 15 permit ::/0 le 128
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
!
end

R14#
